---
name: instagram_flutter
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.15.1 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^1.12.0
  cloud_firestore: ^3.1.7
  firebase_auth: ^3.3.6
  firebase_storage: ^10.2.6
  provider: ^6.0.2
  flutter_staggered_grid_view: ^0.4.1
  file_picker: ^4.3.3
  intl: ^0.17.0
  flutter_svg: ^1.0.3
  flutter_plugin_android_lifecycle: ^2.0.5
  image_picker: ^0.8.4+9
  uuid: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/ic_instagram.svg
